export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const GET_WALLPAPERS = 'GET_FAVOURITE_WALLPAPERS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_FAVOURITE_WALLPAPERS = 'GET_FAVOURITE_WALLPAPERS';
export const SET_FAVOURITE_WALLPAPERS = 'SET_FAVOURITE_WALLPAPERS';
export const DOWNLOADING_START = 'DOWNLOADING_START';
export const DOWNLOADING_END = 'DOWNLOADING_END';
